# Generated by Django 5.0.6 on 2024-05-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filme", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilmeRecomedado",
            fields=[
                (
                    "idFilmeRecomendado",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "idFilme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="filme.filme",
                    ),
                ),
                (
                    "idUsuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="filme.usuario",
                    ),
                ),
            ],
        ),
    ]
