# Generated by Django 5.0.6 on 2024-05-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filme", "0002_filmerecomedado"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="avaliacao",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
