# Generated by Django 5.0.6 on 2024-05-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filme", "0003_filme_avaliacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filme",
            name="avaliacao",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
