# Generated by Django 5.0.6 on 2024-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filme", "0005_filme_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="descricao",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
