# Generated by Django 5.0.6 on 2024-05-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filme", "0006_filme_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="anoMax",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="anoMin",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
